### ISSUE TITLE
Can't obtain dual variable

### ISSUE THREAD

**Issue by Thuener** [jump-dev/Convex.jl#158] opened 2016-08-26 23:00 UTC
The example code in http://convexjl.readthedocs.io/en/latest/advanced.html to get the dual variable doesn't work( tested with gurobi and cplex):

```
using Convex

x = Variable()
constraint = x >= 0
p = minimize(x, constraint)
solve!(p)

# Get the dual value for the constraint
p.constraints[1].dual
# or
constraint.dual
```

**Comment by mlubin** [comment] 2016-08-26 23:13
Duals are not currently available through Gurobi or Cplex. Use SCS, ECOS, or Mosek.

**Comment by Thuener** [comment] 2016-08-26 23:40
OK. I will create a function because I have to use one of these solvers. Seems easy using MathProgBase.getconstrduals(p.model.lpqpmodel). I could add this to the Convex.jl but I'm not familiar with the code.

**Comment by mlubin** [comment] 2016-08-26 23:45
Convex.jl accesses duals through [getdual](http://mathprogbasejl.readthedocs.io/en/latest/conic.html#getdual) in the conic interface. Gurobi and CPLEX are not natively conic solvers, so it will take some work to extract the proper duals. The code that does the translation between conic form and Gurobi/CPLEX is [here](https://github.com/JuliaOpt/MathProgBase.jl/blob/master/src/SolverInterface/lpqp_to_conic.jl).

If you're just solving LPs, you can access duals for Gurobi and CPLEX through JuMP.

**Comment by odow** [comment] 2022-02-23 01:59
Closing as out-dated. This isn't relevant anymore.

**Closed by odow** 2022-02-23 01:59 UTC

**Comment by degleris1** [comment] 2022-03-09 04:04
> Closing as out-dated. This isn't relevant anymore.

@odow Could you elaborate? I've been having the same issue and I'm wondering if it's been resolved.

**Comment by odow** [comment] 2022-03-09 04:14
The issue is from 2016, when Convex.jl used to use MathProgBase. It now uses MathOptInterface to access duals, so the distinction of being unable to get duals for a LP from Gurobi of CPLEX isn't relevant anymore. 

If you have a reproducible example of your issue, please post it on the community forum https://discourse.julialang.org/c/domain/opt/13 and we can discuss. If it's a bug, we can open a new issue.
