### ISSUE TITLE
Error Using the Nuclear Norm

### ISSUE THREAD

**Issue by RoyiAvital** [jump-dev/Convex.jl#701] opened 2024-07-31 14:48 UTC
A simple problem:

```julia
using Convex;
using ECOS;

numRows = 200; #<! Matrix A
numCols = 4;  #<! Matrix A

mA = rand(numRows, numCols);
λ    = 0.5;

mF = Variable(2, 2);
sConvProb = minimize( Convex.sumsquares(mA * Convex.vec(mF)) + λ * Convex.nuclearnorm(mF) );
solve!(sConvProb, ECOS.Optimizer; silent = true);
```

I get the error:

```julia
ERROR: MathOptInterface.UnsupportedConstraint{MathOptInterface.VectorAffineFunction{Float64}, MathOptInterface.NormNuclearCone}: `MathOptInterface.VectorAffineFunction{Float64}`-in-`MathOptInterface.NormNuclearCone` constraint is not supported by the model.
```

On `Julia 1.10.4`, `Convex.jl 0.16.2` on Windows.

**Comment by odow** [comment] 2024-07-31 20:24
ECOS does not support problems with the nuclear norm cone. Try a different solver, like Clarabel.jl.

**Comment by odow** [comment] 2024-07-31 22:42
Closing because this is expected behavior and not a bug in Convex.jl

**Closed by odow** 2024-07-31 22:42 UTC

**Comment by RoyiAvital** [comment] 2024-08-01 03:27
OK, Good to know.
So maybe the error should be different?
As the current error doesn't give such hint to the user.

**Comment by odow** [comment] 2024-08-01 03:50
We should fix the error in https://github.com/jump-dev/MathOptInterface.jl/issues/2528
