### ISSUE TITLE
Convex gives an error with Juniper

### ISSUE THREAD

**Issue by CaG21** [jump-dev/Convex.jl#706] opened 2024-09-27 22:02 UTC
Convex.jl gives an error when a mixed-integer problem is solved with Juniper.

A MWE is the following. The code

```julia
using Convex, Juniper, ECOS
const MOI = Convex.MOI

w = [23; 31; 29; 44; 53; 38; 63; 85; 89; 82]
C = 165
p = [92; 57; 49; 68; 60; 43; 67; 84; 87; 72];
n = length(w)
x = Variable(n, BinVar)
problem = maximize(dot(p, x), dot(w, x) <= C)
opt = MOI.OptimizerWithAttributes(Juniper.Optimizer,
    "nl_solver" => MOI.OptimizerWithAttributes(ECOS.Optimizer, MOI.Silent() => true))
solve!(problem, opt)
```
gives the error

```julia
ERROR: LoadError: MathOptInterface.AddConstraintNotAllowed{MathOptInterface.VectorAffineFunction{Float64}, MathOptInterface.Nonnegatives}: Adding `MathOptInterface.VectorAffineFunction{Float64}`-in-`MathOptInterface.Nonnegatives` constraints cannot be performed: MatrixOfConstraints does not allow modifications to be made to the model once
`MOI.Utilities.final_touch` has been called. This is called at the end of
`MOI.copy_to` and in `MOI.Utilities.attach_optimizer` (which is called by
`MOI.optimize!` in a `MOI.Utilities.CachingOptimizer`). In order to be able to
apply modifications to this model, you should add a layer
`MOI.Utilities.CachingOptimizer(MOI.Utilities.Model{Float64}(), model)`
where `model` is the current model. This will automatically empty `model` when
modifications are done after `MOI.Utilities.final_touch` is called and copy the
model again in `MOI.Utilities.attach_optimizer`.
 You may want to use a `CachingOptimizer` in `AUTOMATIC` mode or you may need to call `reset_optimizer` before doing this operation if the `CachingOptimizer` is in `MANUAL` mode.
```

**Comment by odow** [comment] 2024-09-29 20:16
Okay. This is a bug in Juniper, not Convex. It isn't instantiating the inner solver correctly if it doesn't support incremental updates.

Why Convex for this problem? You're probably better off with JuMP and HiGHS:
```julia
using JuMP, HiGHS
w = [23; 31; 29; 44; 53; 38; 63; 85; 89; 82]
C = 165
p = [92; 57; 49; 68; 60; 43; 67; 84; 87; 72];
model = Model(HiGHS.Optimizer)
@variable(model, x[1:n], Bin)
@objective(model, Max, p' * x)
@constraint(model, w' * x <= C)
optimize!(model)
@assert is_solved_and_feasible(model)
value.(x)
```

If you want MISOCP, use Pajarito:
```Julia
using JuMP, Pajarito, HiGHS, ECOS
w = [23; 31; 29; 44; 53; 38; 63; 85; 89; 82]
C = 165
p = [92; 57; 49; 68; 60; 43; 67; 84; 87; 72];
model = Model(
    optimizer_with_attributes(
        Pajarito.Optimizer,
        "oa_solver" => optimizer_with_attributes(HiGHS.Optimizer, MOI.Silent() => true),
        "conic_solver" => optimizer_with_attributes(ECOS.Optimizer, MOI.Silent() => true),
    ),
)
@variable(model, x[1:n], Bin)
@objective(model, Max, p' * x)
@constraint(model, w' * x <= C)
@variable(model, t)
@constraint(model, [t; x] in SecondOrderCone())
optimize!(model)
@assert is_solved_and_feasible(model)
value.(x)
```
or
```Julia
using Convex, Pajarito, HiGHS, ECOS
import Convex: MOI

w = [23; 31; 29; 44; 53; 38; 63; 85; 89; 82]
C = 165
p = [92; 57; 49; 68; 60; 43; 67; 84; 87; 72];
n = length(w)
x = Variable(n, BinVar)
problem = maximize(dot(p, x), dot(w, x) <= C)
opt = MOI.OptimizerWithAttributes(
    Pajarito.Optimizer,
    "oa_solver" => MOI.OptimizerWithAttributes(HiGHS.Optimizer, MOI.Silent() => true),
    "conic_solver" => MOI.OptimizerWithAttributes(ECOS.Optimizer, MOI.Silent() => true),
)
solve!(problem, opt)
```

**Comment by odow** [comment] 2024-09-30 01:14
Closing because this is not a bug in Convex. I'll open a new issue in Juniper.

**Closed by odow** 2024-09-30 01:14 UTC
