### ISSUE TITLE
quadform objective does not work with OSQP

### ISSUE THREAD

**Issue by a7b** [jump-dev/Convex.jl#709] opened 2024-10-29 06:56 UTC
I was trying to solve the following QP using OSQP:

``` julia 
λs = [0, 0.01, 0.1, 1, 10, 100, 200, 300, 1000]
for i in eachindex(λs)
    n = size(mat, 1) - 1
    x = Variable(n)
    constraints = [sum(x) == 100000, x >= 0]
    p = minimize( 1/2 * quadform(x, Σ) - λs[i] * dot(μr, x), constraints)
    solve!(p, OSQP.Optimizer)
end

```

but I get the error 
> UnsupportedConstraint: `MathOptInterface.VectorAffineFunction{Float64}`-in-`MathOptInterface.SecondOrderCone` constraints are not supported by the
solver you have chosen, and we could not reformulate your model into a
form that is supported. 

Both of the constraints can be written in the form required by OSQP but it seems that Convex.jl is unable to do this. It would be nice if this could be fixed.

**Comment by odow** [comment] 2024-10-29 18:53
What is the output of `import Pkg; Pkg.status()`?

**Comment by odow** [comment] 2024-10-29 18:57
A smaller example:
```julia
julia> begin
           using Convex, OSQP
           x = Variable(2)
           p = minimize(quadform(x, [1 0; 0 1]))
           solve!(p, OSQP.Optimizer)
       end
ERROR: UnsupportedConstraint: `MathOptInterface.VectorAffineFunction{Float64}`-in-`MathOptInterface.SecondOrderCone` constraints are not supported by the
solver you have chosen, and we could not reformulate your model into a
form that is supported.

To fix this error you must choose a different solver.
```

I expected this to work. I haven't looked at the details yet.

**Comment by ericphanson** [comment] 2024-10-29 19:08
I think this is the thing where Convex unconditionally reformulates things, here quadratic to SOC instead of letting MOI do it so it can be appropriate to the solver

**Comment by odow** [comment] 2024-10-29 19:35
Oooh. This is actually a duplicate of https://github.com/jump-dev/Convex.jl/issues/384

I'll close this issue to keep the discussion focused on #384

**Closed by odow** 2024-10-29 19:35 UTC
Labels: bug
